var public_key="-----BEGIN PUBLIC KEY-----"+
"MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDVkXq/WLyQKhgYXJ4Cq5gh65Cj"+
"+0YFtVjJ4jnBNXtnTtOyqiTUf0Klu/cPKSlqYnkNaPQY5m4BOKS3aFAiFpPCRZbI"+
"qNfRCBlUv6wk9U7afl+6cb6NBTzBC4fLh3fhYWtbR+WYMIpj0iIYMPqnpAesCj7i"+
"cj85yZrois0j8fxDtQIDAQAB"+
"-----END PUBLIC KEY-----"
